nameOverride: ""
fullnameOverride: ""

databaseURL: postgres://shop:shop@shop-postgres-rw:5432/shop?sslmode=disable

api:
  replicaCount: 4

  image:
    repository: ghcr.io/shop-lab/api
    tag: v3
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80
    targetPort: 8080

  healthFail: false

  probes:
    liveness:
      initialDelaySeconds: 5
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 2
      periodSeconds: 5

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

worker:
  replicaCount: 2

  image:
    repository: ghcr.io/shop-lab/worker
    tag: v2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080

  pollInterval: 1s

  probes:
    liveness:
      initialDelaySeconds: 5
      periodSeconds: 10
    readiness:
      initialDelaySeconds: 2
      periodSeconds: 5

  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 65532
  runAsGroup: 65532

containerSecurityContext:
  privileged: false
  allowPrivilegeEscalation: false

monitoring:
  enabled: true
  interval: 15s
  scrapeTimeout: 5s
  dashboard:
    enabled: true
  alerts:
    apiUnavailableFor: 1m
    errorRateThreshold: 0.05
    errorRateFor: 2m
    latencyP95Seconds: 1
    latencyFor: 5m

postgres:
  instances: 1

  storage:
    size: 1Gi
    storageClass: local-path

  database: shop
  owner: shop

  credentials:
    username: shop
    password: shop

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
