fullnameOverride: kps

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    scrapeConfigSelectorNilUsesHelmValues: false
    retention: 6h
    scrapeInterval: 15s
    evaluationInterval: 15s
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        memory: 1536Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 25m
        memory: 128Mi
      limits:
        memory: 256Mi
  config:
    global:
      resolve_timeout: 2m
    route:
      group_by: ['alertname', 'service']
      group_wait: 10s
      group_interval: 30s
      repeat_interval: 10m
      receiver: 'webhook-sink'
      routes:
        - matchers:
            - alertname = "Watchdog"
          receiver: 'null'
    receivers:
      - name: 'null'
      - name: 'webhook-sink'
        webhook_configs:
          - url: 'http://alert-sink.obs.svc.cluster.local:8080/'
            send_resolved: true

grafana:
  fullnameOverride: grafana
  adminPassword: admin
  defaultDashboardsEnabled: true
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      memory: 512Mi
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
      label: grafana_dashboard
    datasources:
      defaultDatasourceEnabled: false
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://kps-prometheus.obs.svc.cluster.local:9090
      isDefault: true
      jsonData:
        timeInterval: 15s
    - name: Loki
      type: loki
      uid: loki
      access: proxy
      url: http://loki-gateway.obs.svc.cluster.local
      jsonData:
        derivedFields:
          - name: TraceID
            matcherRegex: '"trace_id":"([a-f0-9]+)"'
            url: '$${__value.raw}'
            datasourceUid: jaeger
    - name: Jaeger
      type: jaeger
      uid: jaeger
      access: proxy
      url: http://jaeger-query.obs.svc.cluster.local:16686

kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeEtcd:
  enabled: false
