apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shop.fullname" . }}-postgres-credentials
  labels:
    {{- include "shop.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.credentials.username | quote }}
  password: {{ .Values.postgres.credentials.password | quote }}
