{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shop.fullname" . }}
  labels:
    {{- include "shop.commonLabels" . | nindent 4 }}
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  jobLabel: app.kubernetes.io/name
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - api
          - worker
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
{{- end }}
