apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: disallow-host-namespaces
spec:
  validationActions:
    - Deny

  matchConstraints:
    resourceRules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - pods

  matchConditions:
    - name: exclude-system-namespaces
      expression: >-
        object.metadata.namespace != "kube-system" &&
        object.metadata.namespace != "kyverno" &&
        object.metadata.namespace != "obs"

  validations:
    - message: >-
        Pods must not use the host network, PID, or IPC namespaces.
      expression: >-
        object.spec.?hostNetwork.orValue(false) == false &&
        object.spec.?hostPID.orValue(false) == false &&
        object.spec.?hostIPC.orValue(false) == false
